export const LAY_DANH_SACH_BAN = "LAY_DANH_SACH_BAN"
export const LAY_CHI_TIET_TANG = "LAY_CHI_TIET_TANG"
export const CHON_BAN = "CHON_BAN"
export const TIM_BAN = "TIM_BAN"
export const RESET_ALL = "RESET_ALL"